flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- QuickCheck-2.10.0.1
- clock-0.7.2
- extra-1.6
- hmatrix-0.18.1.0
- hmatrix-gsl-0.18.0.1
- loop-0.3.0
- matrix-0.3.5.0
- primitive-0.6.2.0
- random-1.1
- split-0.2.3.2
- storable-complex-0.2.2
- tf-random-0.5
- vector-0.12.0.1
resolver: ghc-8.2.1
